# Reference docs at:
# https://docs.codecov.io/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # check only master and branches that should be merged directly into
        # master
        branches:
          - master
          - "feature/*"
          - "release/*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  # comments in the pull request are not preventing the merge, and can be
  # useful to detect dropping in unit and regression tests since they are
  # individually reported [so keep the following option commented]
  #branches:
  #- master
  #- "feature/*"
  #- "release/*"
