package:
    name: dis
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../src

requirements:
    host:
        - numpy
        - python
        - numba
        - scipy
    run:
        - numpy
        - python
        - numba
        - sphinx
        - recommonmark
        - sphinx_rtd_theme
        - scipy
        - pyyaml
        - lhapdf
        - apfel

test:
    requires:
        - pytest
        - conda-build

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://github.com/N3PDF/dis
    license: GPLv3
    summary: "Yet Another Deep Inelastic Scattering Module"
