name: regression

on:
  push:
    branches-ignore:
      - "*docs*"

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - name: Configure git-lfs to ignore most files
        run: |
          git config --global lfs.fetchinclude 'benchmarks/storage/regression.json'
      # checkout the repo on the github runner
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # install the actual python package 'yadism'
      - name: Install yadism
        run: |
          pip install .
      - name: Prepare Test environment
        run: |
          # install packages needed for testing
          pip install -r dev_requirements.txt
          # move db
          head --bytes=20 benchmarks/storage/*
          mv benchmarks/storage/regression.json benchmarks/data/
      #  run the test with 'pytest'
      - name: Test yadism
        run: |
          # run tests
          pytest -m regression
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: regression
          name: codecov-umbrella
          fail_ci_if_error: true
